min_angle: 150
allowable: 5 
evap_rate: 0.1
pher_update:
        window: 5
        win_type: 'triang'

ant:
        neighbours: 4 
        allowable: 5 
        min_angle: 150
        min_pheromone: 0.00001
        dist_weight: 0.5
        angle_weight: 0.5
        alpha: 0.5
        beta: 0.5
